services:
  postgres:
    image: postgres:16-alpine
    container_name: marketplace-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: marketplace
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1245
    ports:
      - "5433:5432"
    volumes:
      - marketplace_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d marketplace"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  marketplace_postgres_data:
